// Test de la instalación de tipos de Cloudflare Workers (REQ-30-01..06,
// feature 30 cloudflare-types-install). Verifica contra
// specs/30_cloudflare-types-install/requirements.md:
//   REQ-30-01 — worker-configuration.d.ts existe en la raíz, WHERE
//               tsconfig.json lo incluye en su lista de tipos.
//   REQ-30-02 — el archivo declara los tipos del runtime de Cloudflare
//               Workers, WHERE el script generate-types los genera con
//               wrangler types.
//   REQ-30-03 — el archivo permanece bajo control de versiones: tsconfig lo
//               incluye, .gitignore no lo excluye y git ls-files lo rastrea.
//   REQ-30-04 — generate-types regenera el archivo de forma idempotente
//               (wrangler types sin modificar su contrato).
//   REQ-30-05 — este test falla cuando el archivo falta, está vacío o deja
//               de rastrearse en git.
//   REQ-30-06 — docs/dependencies.md ampara @cloudflare/workers-types y
//               wrangler como aprobadas por el humano.
//
// Contrato fijado: el archivo existe en la raíz, no está vacío y contiene la
// marca de generación de wrangler ("Generated by Wrangler"), el prefijo
// estable que `wrangler types` v4 produce. REQ-30-04 ejecuta el binario real
// de wrangler (el mismo que ejecuta el script generate-types de package.json,
// REQ-21-02) y exige idempotencia estricta (contenido byte a byte).

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { existsSync, readFileSync, rmSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const ROOT_FILE = new URL('../worker-configuration.d.ts', import.meta.url);
const ROOT_PATH = fileURLToPath(ROOT_FILE);
const TSCONFIG_URL = new URL('../tsconfig.json', import.meta.url);
const GITIGNORE_URL = new URL('../.gitignore', import.meta.url);
const PACKAGE_URL = new URL('../package.json', import.meta.url);
const DEPENDENCIES_URL = new URL('../docs/dependencies.md', import.meta.url);
const WRANGLER_BIN = fileURLToPath(
  new URL('../node_modules/wrangler/bin/wrangler.js', import.meta.url),
);

const CONTRACT = /Generated by Wrangler/;

function gitLsFiles() {
  const ls = spawnSync('git', ['ls-files'], { encoding: 'utf8' });
  assert.equal(ls.status, 0, 'git ls-files falló');
  return ls.stdout.split('\n');
}

test('REQ-30-01/05: worker-configuration.d.ts existe en la raíz y no está vacío', () => {
  assert.ok(
    existsSync(ROOT_PATH),
    'worker-configuration.d.ts no existe en la raíz (REQ-30-01/05)',
  );
  const content = readFileSync(ROOT_FILE, 'utf8');
  assert.ok(content.trim().length > 0, 'worker-configuration.d.ts está vacío (REQ-30-05)');
});

test('REQ-30-02: el archivo declara el contrato de tipos generado por wrangler', () => {
  const content = readFileSync(ROOT_FILE, 'utf8');
  assert.match(
    content,
    CONTRACT,
    'worker-configuration.d.ts no contiene la marca de generación de wrangler (REQ-30-02)',
  );
});

test('REQ-30-03: tsconfig.json incluye el archivo y .gitignore no lo excluye', () => {
  const tsconfig = readFileSync(TSCONFIG_URL, 'utf8');
  assert.ok(
    tsconfig.includes('./worker-configuration.d.ts'),
    'tsconfig.json no incluye ./worker-configuration.d.ts (REQ-30-03)',
  );
  const gitignore = readFileSync(GITIGNORE_URL, 'utf8');
  assert.ok(
    !gitignore.includes('worker-configuration'),
    '.gitignore excluye worker-configuration.d.ts: debe commitearte (REQ-30-03)',
  );
});

test('REQ-30-03/05: git ls-files rastrea el archivo', () => {
  assert.ok(
    gitLsFiles().includes('worker-configuration.d.ts'),
    'git ls-files no rastrea worker-configuration.d.ts (REQ-30-03/05)',
  );
});

test('REQ-30-04: generate-types (wrangler types) regenera el archivo sin modificar su contrato', () => {
  assert.ok(
    existsSync(WRANGLER_BIN),
    'node_modules/wrangler/bin/wrangler.js no existe (generate-types no ejecutable)',
  );
  // Estado previo para restaurarlo si el archivo aún no existía (evidencia
  // roja repetible antes de la implementación, REQ-30-05).
  const existedBefore = existsSync(ROOT_PATH);
  const before = existedBefore ? readFileSync(ROOT_FILE, 'utf8') : '';
  try {
    const run = spawnSync(process.execPath, [WRANGLER_BIN, 'types'], {
      encoding: 'utf8',
      maxBuffer: 8 * 1024 * 1024,
    });
    assert.equal(run.status, 0, `wrangler types falló (REQ-30-04):\n${run.stdout}\n${run.stderr}`);
    assert.ok(existsSync(ROOT_PATH), 'wrangler types no generó worker-configuration.d.ts (REQ-30-04)');
    const after = readFileSync(ROOT_FILE, 'utf8');
    assert.match(after, CONTRACT, 'wrangler types regeneró el archivo sin el contrato (REQ-30-04)');
    if (existedBefore) {
      assert.equal(after, before, 'wrangler types modificó worker-configuration.d.ts (REQ-30-04, idempotencia)');
    }
  } finally {
    if (!existedBefore) {
      rmSync(ROOT_PATH, { force: true });
    }
  }
});

test('REQ-30-06: el registro de dependencias ampara los paquetes de tipos aprobados', () => {
  const registry = readFileSync(DEPENDENCIES_URL, 'utf8');
  for (const name of ['@cloudflare/workers-types', 'wrangler']) {
    assert.ok(
      registry.includes(`### ${name}`),
      `docs/dependencies.md no registra ${name} como aprobada (REQ-30-06)`,
    );
  }
  assert.ok(
    registry.includes('2026-08-13'),
    'docs/dependencies.md no declara la aprobación del 2026-08-13 (REQ-30-06)',
  );
});

test('REQ-30-02/03: package.json declara el script generate-types con wrangler types', () => {
  const pkg = JSON.parse(readFileSync(PACKAGE_URL, 'utf8'));
  assert.equal(
    pkg.scripts?.['generate-types'],
    'wrangler types',
    'package.json no declara generate-types = wrangler types (REQ-21-02/REQ-30-02)',
  );
});